beluga/include/beluga/algorithm/raycasting.hpp, beluga/include/beluga/sensor/beam_model.hpp, beluga/include/beluga/sensor/data/dense_grid.hpp, beluga/include/beluga/sensor/data/linear_grid.hpp, beluga/include/beluga/sensor/data/occupancy_grid.hpp, beluga/include/beluga/sensor/data/regular_grid.hpp, beluga/include/beluga/sensor/data/value_grid.hpp, beluga/include/beluga/sensor/likelihood_field_model.hpp, beluga/run-clang-tidy.sh, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/algorithm/test_raycasting.cpp, beluga/test/beluga/include/beluga/test/static_occupancy_grid.hpp, beluga/test/beluga/sensor/data/test_dense_grid.cpp, beluga/test/beluga/sensor/data/test_linear_grid.cpp, beluga/test/beluga/sensor/data/test_occupancy_grid.cpp, beluga/test/beluga/sensor/data/test_regular_grid.cpp, beluga/test/beluga/sensor/test_beam_model.cpp, beluga/test/beluga/sensor/test_likelihood_field_model.cpp, beluga/test/benchmark/CMakeLists.txt, beluga/test/benchmark/benchmark_raycasting.cpp, beluga_amcl/include/beluga_amcl/occupancy_grid.hpp
Closes #171.
This patch modularizes and deduplicates occupancy grid related code.
=> Rework occupancy grids

GETTING_STARTED.md, beluga/README.md, beluga/include/beluga/algorithm/estimation.hpp, beluga/include/beluga/sensor.hpp
Adds missing documentation links:
- BeamSensorModel in Sensors page
- WeightedStateEstimator in StateEstimation page
Adds a section with a link to the Doxygen documentation from the Beluga README.md (before the only link was in the landing page of the repository).
Also fixes the path to the document generation script in GETTING_STARTED.md
=> Add missing documentation links

beluga/include/beluga/motion/differential_drive_model.hpp, beluga/include/beluga/motion/omnidirectional_drive_model.hpp, beluga/include/beluga/sensor/beam_model.hpp, beluga/include/beluga/sensor/likelihood_field_model.hpp, beluga_benchmark/beluga_benchmark/compare_results.py, beluga_benchmark/docs/BENCHMARKING.md
Removes the `shared_mutex` locks, that were not currently in use since there's no concurrency in how different steps of the filter are applied, but that was causing performance issues.
Pre (before change) and post (after change) performance of the node.
=> Remove shared_mutexes to address concurrency performance

beluga_amcl/README.md, beluga_amcl/docs/PARAMETERS.md, beluga_example/config/params.yaml
This is a follow up to https://github.com/Ekumen-OS/beluga/pull/186#discussion_r1197174185. Also related to #85.
=> Add AMCL parameter reference page

beluga/include/beluga/algorithm/raycasting.hpp, beluga/include/beluga/sensor/beam_model.hpp, beluga/include/beluga/sensor/data/regular_grid.hpp, beluga_amcl/src/amcl_node.cpp
Minor optimizations to the tightest execution loops in the beam sensor model.
While these changes do improve performance a bit, they barely make a difference in the performance disadvantage we have against Nav2 AMCL. We are still missing something much bigger than these optimizations.
These changes change the performance profile, as seen through `perf` from this:
to this:
**Note: These flamegraphs assume the changes in #199 have already been merged, since there are grid optimizations that are common to both Likelihood and Beam.**
Notice that relative to the unmodified the `beluga::Bresenham2i::Line` block of code (that had no changes done to it, neither in performance per …
=> Optimize beam sensor model runtime performance

beluga_amcl/src/amcl_node.cpp
This PR proposes chaging the default threading mode to "sequential" on the basis that while parallel has lower latency, the required increase in CPU usage makes it expensive for users not concerned about latency in the lower end of particle counts. See #193 . 
=> Change default threading mode to the less cpu-consuming one

.lcovrc, beluga_amcl/src/amcl_node.cpp, tools/build-and-test.sh
Related to #101.
GCC records branch information for each line where a scope exit due to some thrown exception is possible. This sets too high a standard for us to meet. C++ templates may also add subtle distortions in coverage measurement, an so do inline functions.
This patch keeps only line coverage data collection while disabling branch and function coverage.
https://stackoverflow.com/a/43726240
=> Disable branch and function coverage

beluga/test/beluga/algorithm/test_raycasting.cpp, beluga/test/beluga/include/beluga/test/raycasting.hpp, beluga/test/benchmark/benchmark_raycasting.cpp
Related to #167.
This patch extends existing microbenchmarks to use as reference to compare the performance of the raycast and occupancy grid implementation.
The baseline raycast and occupancy grid implementations were inspired by `nav2_amcl`.
Command to run:
```bash
colcon build --packages-up-to beluga && ./build/beluga/test/benchmark/benchmark_beluga --benchmark_filter=Ray
```
First results:
```
Running ./build/beluga/test/benchmark/benchmark_beluga
Run on (16 X 3300 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 512 KiB (x8)
L3 Unified 16384 KiB (x1)
Load Average: 0.92, 0.81, 0.76
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead. …
```
=> Extend raycast microbenchmarks

beluga_amcl/src/amcl_node.cpp, beluga_benchmark/beluga_benchmark/compare_results.py, beluga_benchmark/beluga_benchmark/timem_results.py, beluga_benchmark/scripts/benchmarking/parameterized_run, beluga_example/launch/example_rosbag_launch.py
- Changes the tolerance value for the MessageFilter to match the value used by Nav2 (the same value as `transform_tolerance`).
- Fixes a problem in the `compare_results.py` script that causes it to fail to plot a whole series of data if a single bad sample is present (this happens frequently when capturing AMCL performance data in the high-end of particle counts).
- Fix a mismatch in the naming of the `playback_rate` command line argument of the `parameterized_run` script and the launchfile.
- Changes the default playback rate to be 1x to avoid distorting the captured CPU stats.
The following plots show that the performance at 1x replay rate both before and after the change of …
=> Updates and fixes before updating performance report

.codecov.yml, beluga/cmake/Config.cmake.in, beluga/include/beluga/algorithm/estimation.hpp, beluga/include/beluga/algorithm/raycasting/bresenham.hpp, beluga/include/beluga/mixin.hpp, beluga/include/beluga/mixin/utility.hpp, beluga/include/beluga/random/multivariate_normal_distribution.hpp, beluga/include/beluga/sensor/data/occupancy_grid.hpp, beluga/package.xml, beluga/test/beluga/algorithm/raycasting/test_bresenham.cpp, beluga/test/beluga/algorithm/test_estimation.cpp, beluga/test/beluga/include/beluga/test/utils/eigen_initializers.hpp, beluga/test/beluga/include/beluga/test/utils/sophus_matchers.hpp, beluga/test/beluga/mixin/test_utility.cpp, beluga/test/beluga/random/test_multivariate_normal_distribution.cpp, beluga/test/beluga/resampling_policies/test_resample_on_motion_policy.cpp, beluga/test/benchmark/CMakeLists.txt, beluga/test/benchmark/benchmark_main.cpp, beluga/test/benchmark/benchmark_raycasting.cpp
Connected to #95. Before ROS Noetic support, we need `beluga` building on Ubuntu Focal: compiling with `gcc` 9.3, using an older version of Eigen3. This patch performs the necessary compatibility changes, with no functional side effects (or none that I have observed).
(*) Note there is no development container or CI workflow here to validate these changes effectively help in Ubuntu Focal. That'll come in follow-up PRs, to limit scope.
=> Support `beluga` builds on Ubuntu Focal

beluga_amcl/src/amcl_node.cpp, beluga_amcl/test/test_amcl_node.cpp
This bug was not caught before because map to odom in our `perfect_odometry` bag is the identity.
=> Fix map to odom transform calculation

.gitmodules, docker/files/humble.repos, docker/files/rolling.repos, docker/images/humble/Dockerfile, docker/images/rolling/Dockerfile
Related to #95 and mentioned #210.
This patch removes `git submodules` from the repository in favor of `vcstool` so we can better handle dependencies for different ROS versions. Additionally, it makes use of Docker's multistage builds to cache package manifest files.
=> Configure vcstool and use docker multi-stage builds

.github/workflows/ci_pipeline.yml, .github/workflows/docker_ci_pipeline.yml, beluga/CMakeLists.txt, beluga/test/beluga/type_traits/test_strongly_typed_numeric.cpp, docker/images/noetic/Dockerfile, tools/build-and-test.sh, tools/run-clang-tidy.sh
Follow-up PR after #209. This patch adds CI infrastructure to build `beluga` (and only `beluga` for now) against ROS Noetic in Ubuntu Focal.
=> Add ROS Noetic CI infrastructure

beluga_amcl/test/test_amcl_node.cpp
The test added in #212 turned out to be flaky.
The failure rate is ~20% and can be evaluated with this command:
```bash
$ ./build/beluga_amcl/test/test_amcl_node --gtest_repeat=1000 --gtest_filter=TestNode.TransformValue 2> /dev/null | grep "1 FAILED" | wc -l
189
```
The error looks like this:
```bash
/ws/src/beluga/beluga_amcl/test/test_amcl_node.cpp:877: Failure
The difference between transform.translation().x() and -2.00 is 0.010270443192699208, which exceeds 0.01, where
transform.translation().x() evaluates to -2.0102704431926992,
-2.00 evaluates to -2, and
0.01 evaluates to 0.01.
/ws/src/beluga/beluga_amcl/test/test_amcl_node.cpp:878: Failure
The difference between transform.translation().y() and -2.00 is 0.01017702160925138, which exceeds 0.01, where
transform.translation().y() …
```
=> Fix flaky transform test

.github/workflows/ci_pipeline.yml, .github/workflows/docker_ci_pipeline.yml, docker/images/humble/Dockerfile, docker/images/noetic/Dockerfile, docker/images/rolling/Dockerfile
Build `timem` (and only `timem`) in a separate stage in our Dockerfiles.
Use [GitHub Actions cache backend](https://docs.docker.com/build/cache/backends/) in the Docker CI pipeline.
=> Speed up docker builds in CI

beluga_amcl/docs/PARAMETERS.md, beluga_amcl/src/amcl_nodelet.cpp, beluga_example/params/default.ros.yaml
As stated in the compatibility notes, Beluga AMCL actually implements `diff-corrected` and `omni-corrected` motion models. This change is necessary so that we run the same models when using the same parameters in Navigation AMCL.
=> Rename motion models in Beluga AMCL for ROS 1

.cmake-format, .pre-commit-config.yaml, beluga/CMakeLists.txt, beluga/docs/CMakeLists.txt, beluga/test/CMakeLists.txt, beluga/test/beluga/CMakeLists.txt, beluga/test/benchmark/CMakeLists.txt, beluga_amcl/CMakeLists.txt, beluga_amcl/cmake/ament.cmake, beluga_amcl/cmake/catkin.cmake, beluga_amcl/cmake/lib/nodelets.cmake, beluga_amcl/package.xml, beluga_amcl/test/CMakeLists.txt, beluga_amcl/test/cmake/ament.cmake, beluga_amcl/test/cmake/catkin.cmake, beluga_benchmark/CMakeLists.txt, beluga_example/CMakeLists.txt, beluga_example/cmake/ament.cmake, beluga_example/cmake/catkin.cmake, beluga_example/package.xml, beluga_system_tests/CMakeLists.txt, beluga_system_tests/test/CMakeLists.txt
=> Add cmake-format to pre-commit hooks

beluga_example/bags/perfect_odometry/metadata.yaml
Fixes #232.
This patch fixes message timestamps and starting time in the rosbag to match the header stamps recorded with sim time.
* The contents of the messages were not altered.
* <del>The storage backend was changed to mcap.</del>
* The last messages where there was a collision against one of the walls were deleted.
=> Fix `perfect_odometry` rosbag

beluga_amcl/config/Amcl.cfg, beluga_amcl/src/amcl_node.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_amcl/test/test_amcl_nodelet.cpp
This is a minor patch to make default params match the navigation AMCL values in ROS 1 and ROS 2. This is convenient for users migrating from the AMCL node provided by the navigation stack, if they define a parameter file that does not mention all parameters, they can expect the behavior to match that of the navigation AMCL node.
=> Change default AMCL params

beluga_amcl/README.md, beluga_amcl/include/beluga_amcl/filter_update_control/filter_update_control_mixin.hpp, beluga_amcl/include/beluga_amcl/private/amcl_node.hpp, beluga_amcl/include/beluga_amcl/private/amcl_nodelet.hpp, beluga_amcl/src/amcl_node.cpp, beluga_amcl/src/amcl_nodelet.cpp, beluga_amcl/test/filter_update_control/test_filter_update_control_mixin.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_system_tests/test/test_system.cpp, docker/images/noetic/Dockerfile
Major changes:
- Fixes lack of pose/transform update when setting a new initial pose.
- Add `request_nomotion_update` service (address #184)
Minor changes:
- Fix that ccache was not being used when building ROS 1.
- Rename `initialize_with_pose()` in `amcl_nodelet.xpp` to `reinitialize_with_pose()`, which is the name of the same function in `amcl_node.xpp`. The old name also overloaded the name of a different function.
=> Fix missing control to force a filter update on pose updates

docker/docker-compose.yml, docker/images/humble/Dockerfile, docker/images/iron/Dockerfile, docker/images/rolling/Dockerfile
- Fixes #250 
- Removes the temporary fixes for #123 , since they don't seem to be necessary anymore
=> Fix glx error issue starting rviz in Noetic/20.04

beluga_benchmark/beluga_benchmark/compare_results.py, beluga_benchmark/docs/BENCHMARKING.md
Add small code snippet to enable saving benchmark scripts data to a csv file instead of plotting.
=> Add option to compare_results.py to save data to csv instead of plotting

beluga/include/beluga/storage.hpp, beluga/test/beluga/test_storage.cpp
Pretty much what the title says. This patch fully initializes a particle cloud in the background before replacing the one in foreground.
The rationale for double buffering stems from the use of ranges for particle cloud initialization during resampling. Since range evaluation is lazy, the resampling algorithm would end up reading from the same particle set it is mutating, skewing the results. 
[Nav2 AMCL is careful about this](https://github.com/ros-planning/navigation/blob/9ad644198e132d0e950579a3bc72c29da46e60b0/amcl/src/amcl/pf/pf.c#L377-L378). We were not (and that's how I realized).
=> Use double buffering in particle storage

beluga/include/beluga/motion/differential_drive_model.hpp, beluga/test/beluga/motion/test_differential_drive_model.cpp
Going over the math a few times, it doesn't seem to me that the rotation variance computation distributes over rotation composition. Not with those nonlinear max, min, abs operations in between.
Not sure how to write a test for this. Would a formal proof (that `rotation_variance(a) * rotation_variance(b) != rotation_variance(a * b)`) do?
=> Fix differential drive motion model

beluga/include/beluga/interfaces/bearing_sensor_model_interface.hpp, beluga/include/beluga/interfaces/landmark_sensor_model_interface.hpp, beluga/include/beluga/interfaces/laser_sensor_model_interface_2d.hpp, beluga/include/beluga/sensor.hpp, beluga/include/beluga/sensor/bearing_sensor_model.hpp, beluga/include/beluga/sensor/data/landmark_map.hpp, beluga/include/beluga/sensor/landmark_sensor_model.hpp, beluga/include/beluga/types/landmark_detection_types.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/sensor/data/test_landmark_map.cpp, beluga/test/beluga/sensor/test_beam_model.cpp, beluga/test/beluga/sensor/test_bearing_sensor_model.cpp, beluga/test/beluga/sensor/test_landmark_sensor_model.cpp, beluga/test/beluga/sensor/test_likelihood_field_model.cpp, beluga_amcl/include/beluga_amcl/particle_filtering.hpp, beluga_amcl/src/amcl_node.cpp, beluga_system_tests/test/test_system.cpp
- Adds a slightly polished version of the landmark and bearing sensor models created during last week's hackaton.
- Both have been extended to both 2D and 3D particle states (since it was trivial).
- Tests have been improved.
- A residual bug in the bearing model was found and fixed.
- Minor refactoring to avoid crowding the `sensors.hpp` file with interfaces.
=> Add new discrete landmark and bearing sensor models to the beluga library

beluga/include/beluga/algorithm/spatial_hash.hpp, beluga/test/beluga/test_spatial_hash.cpp
Adds two commits:
- The first one adds periodicity checks that the existing hash function does not pass.
- The second one updates the hash function to pass old and new tests.
Based on:
- https://en.wikipedia.org/wiki/Hash_function#Fibonacci_hashing
- https://probablydance.com/2018/06/16/fibonacci-hashing-the-optimization-that-the-world-forgot-or-a-better-alternative-to-integer-modulo/
=> Improve spatial_hash function to avoid spatial periodicity in the hash function

.clang-tidy, beluga/include/beluga/algorithm/sampling.hpp, beluga/include/beluga/storage.hpp, beluga/include/beluga/type_traits/particle_traits.hpp, beluga/include/beluga/views/take_while_kld.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/algorithm/test_particle_filter.cpp, beluga/test/beluga/algorithm/test_sampling.cpp, beluga/test/beluga/test_storage.cpp, beluga/test/beluga/views/test_take_while_kld.cpp, beluga/test/benchmark/benchmark_sampling.cpp
This patch adds a new particle filter view to take samples based on the KLD condition. This decouples the algorithm implementation from the specific mixin class that we currently use.
=> Add take_while_kld view

beluga/include/beluga/views/random_intersperse.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/views/test_random_intersperse.cpp
This patch adds a new random intersperse view to help with adaptive sampling and replace the `make_random_selector` implementation. This is a range adaptor object that will insert values from a generator function between contiguous elements from the source range based on a given probability.
=> Add random intersperse view

beluga/include/beluga/mixin/sampling.hpp, beluga/include/beluga/mixin/storage.hpp, beluga/include/beluga/tuple_vector.hpp, beluga/include/beluga/type_traits/tuple_traits.hpp, beluga/test/beluga/test_tuple_vector.cpp, beluga/test/benchmark/benchmark_take_while_kld.cpp, beluga/test/benchmark/benchmark_tuple_vector.cpp
=> Add support for tuple vector assignment and conversion

beluga/include/beluga/tuple_vector.hpp, beluga/include/beluga/views.hpp, beluga/include/beluga/views/zip.hpp, beluga/test/beluga/test_tuple_vector.cpp
Fixes `ranges::range_value_t<beluga::TupleVector>` returning a `ranges::common_tuple` instead of `std::tuple`.
=> Add zip view and fix tuple vector traits

beluga/include/beluga/actions.hpp, beluga/include/beluga/actions/assign.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/actions/test_assign.cpp
View-action composition in the range library is limited. This patch implements a new range adaptor object that can be appended to any view closure to evaluate it eagerly and assign the result to a given range, effectively converting any view into an action.
The simple particle filter pipeline example becomes:
```cpp
struct Particle {
int state;
double weight;
};
auto particles = std::vector<Particle>{};
auto motion_model = ...;
auto sensor_model = ...;
particles |= beluga::actions::propagate(motion_model) |
beluga::actions::reweight(sensor_model) |
beluga::views::sample |
ranges::views::take_exactly(1000) |
beluga::actions::assign;
```
=> Add assign action

beluga/include/beluga/actions.hpp, beluga/include/beluga/actions/propagate.hpp, beluga/include/beluga/actions/reweight.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/actions/test_propagate.cpp, beluga/test/beluga/actions/test_reweight.cpp
=> Add propagate and reweight actions

beluga_system_tests/test/CMakeLists.txt, beluga_system_tests/test/test_system_new.cpp
This patch adds a new system test with the new range-based API to run a cartesian product of a list of particle filter variants, sensor models, and motion models. This new test doesn't depend on beluga_amcl code.
It is meant to drive the development of the new API by highlighting its current shortcomings when implementing a complete filter.
You'll see a bunch of TODOs, please let me know if you agree with them.
=> Add system tests with the range-based API

beluga/include/beluga/views/sample.hpp, beluga/test/beluga/views/test_sample.cpp, beluga_system_tests/test/test_system_new.cpp
This saves lines of code by extending the sample view implementation to convert any random distribution (a callable that takes a URNG as an input argument) into a range.
It also makes the implementation easier to follow by removing the use of default arguments (which play poorly with overloads).
=> Extend sample view to sample from random distributions

beluga/docs/doxygen_cites.bib, beluga/include/beluga/random/multivariate_distribution_traits.hpp, beluga/include/beluga/random/multivariate_normal_distribution.hpp, beluga/test/beluga/random/test_multivariate_normal_distribution.cpp, beluga_system_tests/test/test_system.cpp, beluga_system_tests/test/test_system_new.cpp
As the title says, this patch extends the multivariate normal distribution type to support row vectors, SO2, and SE2 elements as different representations of the result type.
=> Extend multivariate distribution to support different result types

beluga/include/beluga/actions/propagate.hpp, beluga/include/beluga/localization.hpp, beluga/include/beluga/motion.hpp, beluga/include/beluga/motion/differential_drive_model.hpp, beluga/include/beluga/motion/omnidirectional_drive_model.hpp, beluga/include/beluga/motion/stationary_model.hpp, beluga/include/beluga/type_traits/tuple_traits.hpp, beluga/test/beluga/motion/test_differential_drive_model.cpp, beluga/test/beluga/motion/test_omnidirectional_drive_model.cpp, beluga/test/beluga/type_traits/test_tuple_traits.cpp, beluga_system_tests/test/test_system_new.cpp
This patch migrates motion models to a functional form. Combined with #320, this affords:
```c++
beluga::actions::propagate(std::execution::par, motion(control_action_window << odom))
```
when propagating particles.
=> Migrate motion models to functional form

beluga/include/beluga/localization.hpp, beluga/include/beluga/sensor.hpp, beluga/include/beluga/sensor/beam_model.hpp, beluga/include/beluga/sensor/bearing_sensor_model.hpp, beluga/include/beluga/sensor/landmark_sensor_model.hpp, beluga/include/beluga/sensor/likelihood_field_model.hpp, beluga/test/beluga/sensor/test_beam_model.cpp, beluga/test/beluga/sensor/test_bearing_sensor_model.cpp, beluga/test/beluga/sensor/test_landmark_sensor_model.cpp, beluga/test/beluga/sensor/test_likelihood_field_model.cpp, beluga_system_tests/test/test_system_new.cpp
Depends on #324. This patch migrates sensor models to a functional form. This affords:
```c++
beluga::actions::reweight(std::execution::par, sensor(std::move(measurement)))
```
when reweighting particles.
=> Migrate sensor models to functional form

beluga/include/beluga/sensor/bearing_sensor_model.hpp, beluga/include/beluga/sensor/landmark_sensor_model.hpp, beluga/test/beluga/sensor/test_bearing_sensor_model.cpp, beluga/test/beluga/sensor/test_landmark_sensor_model.cpp
The sum-of-cubes-plus-1 formula works really bad for landmark models, causing them almost not throw particles that don't really fit what the sensors see, because the high and low values of the probability is not really very different if the number of landmarks is low.
=> Fix landmark models probability aggregation formula

beluga/CMakeLists.txt, beluga/include/beluga/algorithm/thrun_recovery_probability_estimator.hpp, beluga/include/beluga/random/multivariate_uniform_distribution.hpp, beluga/include/beluga/views/sample.hpp, beluga/include/beluga/views/zip.hpp, beluga/test/beluga/algorithm/test_thrun_recovery_probability_estimator.cpp, beluga/test/beluga/sensor/data/test_linear_grid.cpp, beluga/test/beluga/views/test_sample.cpp, beluga_amcl/include/beluga_amcl/amcl_nodelet.hpp, beluga_amcl/src/amcl_nodelet.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_amcl/test/test_amcl_nodelet.cpp, tools/build-and-test.sh
This makes it so we can test our assertions on CI and not run into surprises when trying to create a build with debugging information.
=> Add death tests and build in debug mode

docker/run.sh
When developing, it's convenient to preserve the container status to keep the builds hot and command history present.
This PR adds such functionality to the `docker/run.sh` script.
=> Make dev container run in detached mode

beluga/CMakeLists.txt, beluga/cmake/Config.cmake.in, beluga/package.xml, docker/run.sh
Needed to work in #309 as our NDT generated maps are in HDF5 format. 
=> Add HDF5 dependency to beluga core

.clang-tidy
The way `clang-format` sorts includes conflicts with `clang-tidy`'s, and can only be fixed by the user including empty lines between include blocks in a non intuitive manner.
This PR removes the sorting behavior of `clang-tidy` and will delegate that functionality solely to `clang-format`.
=> Clang tidy doesn't sort includes

.codecov.yml
As the title says, this reduces the amount of false positives in detecting test coverage regressions.
=> Allow coverage to drop by 1%

beluga_example/README.md, beluga_example/colcon.pkg, beluga_example/package.xml, docs/getting-started/installation.md, docs/getting-started/quickstart.md
This patch separates the Flatland dependency from the usual ROS workflow, documenting the necessary steps to satisfy it when and if necessary. This should fix the recent breakage in Beluga doc jobs up in the ROS buildfarm (e.g. [Hdev](https://build.ros2.org/job/Hdev__beluga__ubuntu_jammy_amd64/1/display/redirect), [Idev](https://build.ros2.org/job/Idev__beluga__ubuntu_jammy_amd64)).
=> Isolate Flatland dependency

beluga_benchmark/CMakeLists.txt
Alternative to #369. No other package besides `beluga_benchmark` uses `ament_lint`. We use `pre-commit` hooks instead. This patch removes the dependency altogether.
=> Drop ament_lint_auto dependencies

beluga/test/beluga/algorithm/test_amcl_core.cpp
This fixes a bug in a test where we only sometimes would exercise random state generation, causing line coverage inconsistencies between PRs and the main branch.
This fixes the -0.09% coverage difference we occasionally see in PRs and master merge runs.
=> Ensure we exercise random state generation every time

beluga_amcl/include/beluga_amcl/amcl_node.hpp, beluga_amcl/include/beluga_amcl/amcl_nodelet.hpp, beluga_amcl/include/beluga_amcl/ndt_amcl_node.hpp, beluga_amcl/src/amcl_node.cpp, beluga_amcl/src/amcl_nodelet.cpp, beluga_amcl/src/ndt_amcl_node.cpp
This is a massive bug that escaped our regression testing. We need performance testing in CI ASAP.
=> Fix tf broadcasting

beluga_amcl/docs/ros2-reference.md, beluga_amcl/include/beluga_amcl/amcl_node.hpp, beluga_amcl/include/beluga_amcl/ndt_amcl_node.hpp, beluga_amcl/include/beluga_amcl/ros2_common.hpp, beluga_amcl/src/amcl_node.cpp, beluga_amcl/src/ndt_amcl_node.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_amcl/test/test_ndt_amcl_node.cpp
This patch adds an `autostart` feature for `beluga_amcl` nodes to configure and activate themselves on demand, providing for systems that lack (or avoid) lifecycle management. It is also a escape hatch for Beluga to be usable in ROS 2 without explicitly providing a `nav2_lifecycle_manager` substitute.
=> Enable beluga_amcl ROS 2 nodes' autostart

beluga/include/beluga/algorithm/spatial_hash.hpp, beluga_amcl/docs/ros2-reference.md, beluga_amcl/include/beluga_amcl/amcl_node.hpp, beluga_amcl/src/amcl_node.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_amcl/test/test_utils/node_testing.hpp, beluga_ros/cmake/ament.cmake, beluga_ros/cmake/catkin.cmake, beluga_ros/docs/_doxygen/beluga_ros-main.md, beluga_ros/include/beluga_ros/beluga_ros.hpp, beluga_ros/include/beluga_ros/messages.hpp, beluga_ros/include/beluga_ros/particle_cloud.hpp, beluga_ros/include/beluga_ros/tf2_eigen.hpp, beluga_ros/package.xml, beluga_ros/test/test_messages.cpp, beluga_ros/test/test_particle_cloud.cpp
Follow-up to #372. As the title reads, this restores the functionality we had with `nav2_msgs/ParticleCloud` using `visualization_msgs/MarkerArray` instead.
https://github.com/Ekumen-OS/beluga/assets/13500507/9b4e84b8-0b27-40cd-a052-63f1ef91dadb
=> Restore particle cloud visualization using markers

.github/workflows/ci_pipeline.yml, .github/workflows/docker_ci_pipeline.yml, .github/workflows/weekly_pipeline.yml, beluga/test/beluga/motion/test_differential_drive_model.cpp, beluga/test/beluga/motion/test_omnidirectional_drive_model.cpp, beluga_amcl/src/amcl_node.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_amcl/test/test_ndt_amcl_node.cpp, beluga_example/package.xml, docker/docker-compose.yml, docker/files/jazzy.repos, docker/images/jazzy/Dockerfile, tools/build-and-test.sh, tools/run-clang-tidy.sh
Precisely what the title says. This patch also fixes the tests that started failing with the transition.
Here we exclude `beluga_example` and `beluga_benchmark`, as we cannot yet satisfy nav2 dependencies.
=> Add ROS 2 Jazzy to CI/CD and dev workflows

beluga/include/beluga/type_traits/particle_traits.hpp, beluga/test/beluga/views/test_sample.cpp
This change improves compatibility with older GCC versions (9.3) that struggle to deduce the type of instantiated template functions when they are passed as arguments.
Minimal examples that checks compatibility with GCC 9.3:
Before: https://godbolt.org/z/b1EzfKa75
After: https://godbolt.org/z/9eYzWhEqK
=> Rewrite `make_from_state` as a function object

beluga/include/beluga/algorithm/spatial_hash.hpp
This change improves compatibility with 32-bit platforms (`armhf`).
Trying to fix https://build.ros.org/job/Nbin_ufhf_uFhf__beluga__ubuntu_focal_armhf__binary/4/console.
=> Support 32-bit hashes

beluga/include/beluga/eigen_compatibility.hpp, beluga/include/beluga/sensor/data/dense_grid.hpp, beluga/include/beluga/sensor/data/linear_grid.hpp, beluga/include/beluga/sensor/data/occupancy_grid.hpp, beluga/include/beluga/sensor/data/regular_grid.hpp, beluga/include/beluga/sensor/data/sparse_value_grid.hpp, beluga/include/beluga/sensor/ndt_sensor_model.hpp, beluga/test/beluga/sensor/data/test_dense_grid.cpp, beluga/test/beluga/sensor/data/test_regular_grid.cpp, beluga/test/beluga/sensor/data/test_sparse_value_grid.cpp, beluga/test/beluga/sensor/test_ndt_model.cpp, beluga_amcl/include/beluga_amcl/ndt_amcl_node.hpp
Adds support for N dimensional data structures in some grid types. 
Partially addresses #341  
=> Expand grid concepts to n dimensions

beluga/CMakeLists.txt, beluga/test/beluga/sensor/test_bearing_sensor_model.cpp, beluga/test/beluga/sensor/test_landmark_sensor_model.cpp, tools/run-clang-tidy.sh
This allows running clang-tidy with googletest 1.10 and avoids the unrecognized argument error in GCC 9.4 on the armhf platform.
Closes #389.
Attempt to fix https://build.ros.org/job/Nbin_ufhf_uFhf__beluga__ubuntu_focal_armhf__binary/9/consoleFull.
=> Use `no-gnu-zero-variadic-macro-arguments` only with `clang-tidy`

beluga/include/beluga/random/multivariate_distribution_traits.hpp, beluga/test/beluga/random/test_multivariate_normal_distribution.cpp
Adds support for SE3 and SO3 elements in multivariate normal distribution.
Closes #398. 
Rotations in Lie groups don't have infinite support, and thus the term 'normal' distribution is inherently incorrect.
This approach just follows the `SO2/SE2` approach which faces the same problems as the 3D case.
See some analysis below on how the resulting rotations in SO3 distribute close to normally  for reasonably small covariances:
The plot below shows KDE histograms and Q-Q plots for a diagonal covariance matrix of 
```
{1e-2, 1e-2, 1e-2}
```
and drawing 1000 samples using the approach that was implemented in this PR.
Running the [shapiro](https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test) test shows that the rotation components of the samples seem drawn from a normal distribution with a …
=> Add SO3 and SE3 support for multivariate normal distribution

beluga/include/beluga/3d_embedding.hpp, beluga/include/beluga/motion/differential_drive_model.hpp, beluga/include/beluga/motion/stationary_model.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/motion/test_differential_drive_model.cpp, beluga/test/beluga/test_3d_embedding.cpp, beluga_amcl/include/beluga_amcl/ndt_amcl_node.hpp, beluga_ros/include/beluga_ros/amcl.hpp, beluga_system_tests/test/test_system.cpp
Provides functionality to use SE3d states for the Differential Drive model, by performing some Z flattening and using the underlying 2D motion model.
Closes #399 .
=> Add planar 3D support for `DifferentialDriveModel`

beluga/include/beluga/algorithm/estimation.hpp, beluga/test/beluga/algorithm/test_estimation.cpp
This isn't as much of a fix as it is a minor API contract correction for consistency with the rest. Every other `beluga::estimate` overload trades on variances, but the scalar one introduced in #340 didn't. This patch amends that.
=> Change scalar `beluga::estimate()` to yield variance

beluga_tutorial/params/tutorial.yaml, beluga_tutorial/src/main.cpp
Precisely what the title says. This patch updates `beluga_tutorial` comments and variable names to have a consistent nomenclature.
Depends on #405.
=> Polish `beluga_tutorial` nomenclature for consistency

DEVELOPING.md, docker/images/humble/Dockerfile, docker/images/iron/Dockerfile, docker/images/jazzy/Dockerfile, docker/images/noetic/Dockerfile, docker/images/rolling/Dockerfile
Minor fixes to the docker image to fix #382 
Tested building on Raspberry 4B and Raspberry 5.
=> Fixes to get docker to build in arm64

beluga/include/beluga/algorithm.hpp, beluga/include/beluga/algorithm/cluster_based_estimation.hpp, beluga/include/beluga/algorithm/estimation.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/algorithm/test_cluster_based_estimation.cpp
Addresses #258 and #172.
Add new cluster based estimator. 
- Splits the space in a grid and determines the accumulated weight in each cell.
- Starting from the weight peaks, it groups cells into clusters of ever decreasing weight. It creates as many clusters as needed to cover all the particle occupied space.
- Estimates mean and covariance for each.
- Returns the mean and covariance of the cluster with the highest cumulative weight.
=> Add cluster based estimator

.github/workflows/ci_pipeline.yml
Ci pipeline is broken in master because of a `with` clause in the wrong step. 
Why did this get through CI? @nahueespinosa FYI
=> Remove 'with' statement in CI workflow

beluga/include/beluga/algorithm.hpp, beluga/include/beluga/algorithm/unscented_transform.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/algorithm/test_unscented_transform.cpp
Implements the `Unscented Transform`, very useful when transforming unscertain estimates through (possibly non linear) transform functions.
=> Implement unscented transform `UT`

docker/images/jazzy/Dockerfile, docker/images/rolling/Dockerfile
This patch removes the `ubuntu` user from Noble containers, in order to avoid `fixuid` from clashing with it. Other than system level users, there should only be a `developer` user in development containers.
=> Drop Ubuntu user from Noble containers

docs/getting-started/installation.md
I added a little reminder about sourcing the environment after building the workspace in docs/installation.md.
I noticed that `DEVELOPING.md` is not in the documentation webpage. Is there any reason for this? If not, I could add it.
=> Add a reminder in docs/installation: source the environment

docker/images/jazzy/Dockerfile, docker/images/rolling/Dockerfile
Follow-up to #378. Not all package dependencies were brought in by `rosdep install`. This patch amends that.
=> Install all package deps on Noble containers

beluga/include/beluga/sensor/likelihood_field_model.hpp, beluga/test/beluga/sensor/test_likelihood_field_model.cpp
Initially, this changes likelihood storage from double to float, inspired by https://github.com/ros-navigation/navigation2/pull/4426 . 
More importantly, this fixes a bug in the `make_likelihood_field()` function which causes memory footprint to go through the roof for large maps.
Basically, because we applied the `max_obstacle_distance` threshold **before** calculating the distance map,  for distances larger than  `max_obstacle_distance`  the priority queue in `nearest_obstacle_distance_map()` was processing  the map in a random fashion instead of the "advancing wavefront" that the algorithm is meant to do. This caused the priority queue length to be at least as large as the map itself  and even larger for some maps.
This change does not affect either the accuracy or the average CPU …
=> Fix memory usage problem in 2D likelihood sensor model

docker/docker-compose.yml, docker/run.sh
Follow-up to #173. Hopefully this time around we get multi-platform development containers right.
=> Use per ROS distro dev containers

beluga/include/beluga/views/take_evenly.hpp, beluga/test/beluga/views/test_take_evenly.cpp
Avoids using a range pipeline to implement the take_evenly view which is not great for compile times.
This implementation also makes it a random access view when the underlying range is random access.
=> Rewrite take_evenly view

beluga/include/beluga/actions/normalize.hpp, beluga/test/beluga/actions/test_normalize.cpp, beluga_tutorial/src/main.cpp
Trying a new way of implementing actions that gets rid of the argument re-ordering madness and is hopefully easier to maintain.
=> Rewrite normalize action

beluga_ros/cmake/ament.cmake, beluga_ros/cmake/catkin.cmake, beluga_ros/include/beluga_ros/amcl.hpp, beluga_ros/src/amcl.cpp
Related to #385.
Improves memory usage during compilation of the classic amcl node.
The total memory usage does not improve when compiling the whole `beluga_amcl` package as the NDT nodes are the bottleneck now. I will work on that in follow-up PRs.
=> Convert `beluga_ros` from header-only to a compiled library

.clang-tidy, beluga/include/beluga/algorithm/amcl_core.hpp, beluga/include/beluga/algorithm/cluster_based_estimation.hpp, beluga/include/beluga/algorithm/estimation.hpp, beluga/test/beluga/algorithm/test_cluster_based_estimation.cpp, beluga/test/beluga/algorithm/test_estimation.cpp, beluga/test/beluga/random/test_multivariate_normal_distribution.cpp
Related to #385.
As the title says, refactors the estimation library to reduce compile times, improve consistency, and make it easier to extend.
💥 **Breaking change!** `beluga::calculate_covariance` is `beluga::covariance` and the algorithms are niebloids now.
There is room for improvement around this design (i.e. optional return types, more overloads).
=> Refactor estimation library

docs/guides/extending-beluga.md
Closes #306 . This patch adds a guide on how to extend Beluga. I covered the fraction of the library that is the most stable regarding patterns and architecture and also the most likely one for a user to extend -- new kinds of particles filters or support abstractions I skipped.
=> Add user guide on how to extend Beluga

beluga_ros/include/beluga_ros/particle_cloud.hpp, beluga_ros/test/test_particle_cloud.cpp
Expand the already implemented almost_equal_to function for comparisons of SE3 transformations.
If this look good, I will proceed to create the tests.
=> Add almost_equal_to in SE3

DEVELOPING.md
Add missing step in DEVELOPING.md
=> Minor fix to DEVELOPING.md

CONTRIBUTING.md
This PR just changes a broken link on the docs that was pointing to a `GETTING_STARTED.md` file that doesn't exist anymore. The Table of Content of the file was updated automatically when saving.
=> Fix link to DEVELOPING.md

beluga/include/beluga/algorithm/distance_map.hpp, beluga/include/beluga/sensor/likelihood_field_model.hpp, beluga/test/beluga/algorithm/test_distance_map.cpp, beluga/test/beluga/sensor/test_lfm_with_unknown_space.cpp
Addresses #468 
Also fixes #472 
=> Fix to likelihood map pre-calculation performance for large maps

beluga_amcl/src/amcl_node.cpp, beluga_amcl/src/ros2_common.cpp
=> Add ros parameter for bond timeout

beluga/include/beluga/3d_embedding.hpp, beluga_vdb/include/beluga_vdb/sensor/vdb_likelihood_field_model.hpp, beluga_vdb/test/beluga_vdb/CMakeLists.txt, beluga_vdb/test/beluga_vdb/sensor/test_vdb_likelihood_field_model.cpp
Changed the StateType of the likelihood field sensor model in `beluga_vdb` to a template in order to be able to use it with 2D motion models. And avoid issues like [#478  Unscented transform assertion when using 2.5D covariance matrix](https://github.com/Ekumen-OS/beluga/issues/478)
I changed the name of the sensor from `LikelihoodFieldModel3` to `VDBLikelihoodFieldModel` because I think it might be confusing, since the model will accept 2D particles.
=> Add 2D state type to likelihood field sensor model for beluga_vdb

beluga/include/beluga/sensor.hpp, beluga/include/beluga/sensor/likelihood_field_model_base.hpp, beluga/include/beluga/sensor/likelihood_field_prob_model.hpp, beluga/test/beluga/CMakeLists.txt, beluga/test/beluga/sensor/test_likelihood_field_model_base.cpp, beluga/test/beluga/sensor/test_likelihood_field_prob_model.cpp, beluga_amcl/src/amcl_node.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_ros/include/beluga_ros/amcl.hpp, beluga_ros/src/amcl.cpp
The `LikelihoodFieldProb` sensor model is incorporated, based on the implementation presented in the book Probabilistic Robotics. To achieve this, the `LikelihoodFieldModelCommon` class is created, which implements the Likelihood Field shared by both the `LikelihoodFieldProb` and `LikelihoodField` models.
The `LikelihoodFieldProb` model, in addition to following the book's implementation, includes the summation of the logarithm of probabilities to prevent underflow when multiplying numerous small probabilities. Additionally, the Cluster-Based Estimation algorithm is integrated, enhancing the model's robustness against unmapped objects.
Furthermore, unit tests are implemented for the `LikelihoodFieldProb` sensor model.
_Put an `x` in the boxes that apply. This is simply a reminder of what …
=> Add likelihood prob sensor model and enable Beluga's flavour of clustering

beluga/include/beluga/sensor/likelihood_field_model_base.hpp, beluga/include/beluga/sensor/primitives.hpp, beluga_amcl/config/Amcl.cfg, beluga_amcl/include/beluga_amcl/ros2_common.hpp, beluga_amcl/src/amcl_node.cpp, beluga_amcl/src/amcl_nodelet.cpp, beluga_amcl/src/ros2_common.cpp, beluga_amcl/test/test_amcl_node.cpp, beluga_example/params/default.ros.yaml, beluga_example/params/default.ros2.yaml, beluga_ros/include/beluga_ros/amcl.hpp, beluga_ros/include/beluga_ros/likelihood_field.hpp, beluga_ros/src/amcl.cpp
Expose `model_unknown_space` parameter of the Likelihood Field sensor model to Beluga AMCL (ROS 2). 
=> Expose model_unknown_space parameter to ROS2
