beluga/include/beluga/localization.hpp
beluga/include/beluga/sensor.hpp
beluga/include/beluga/sensor/beam_model.hpp
beluga/include/beluga/sensor/likelihood_field_model.hpp
beluga/test/beluga/sensor/test_beam_model.cpp
beluga/test/beluga/sensor/test_likelihood_field_model.cpp
beluga_amcl/include/beluga_amcl/private/amcl_node.hpp
beluga_amcl/src/amcl_node.cpp
beluga_system_tests/test/test_system.cpp

Related to #85.
This patch exposes a map update API for `beluga::LaserLocalizationInterface2d` compatible filters, and makes use of it in `beluga_amcl` to support map updates on an existing particle filter. Built on top of #188.

Add support for map updates in laser localization filters

---

.codecov.yml
beluga_amcl/src/amcl_node.cpp
beluga_amcl/test/CMakeLists.txt
beluga_amcl/test/test_amcl_node.cpp

Related to #101, this adds tests for the AMCL node up to 95% line coverage. It also fixes a couple of issues with lifecycle management and removes the read_only property for parameters that can change at runtime.
<del>This is still work-in-progress.</del>

Add tests for the AMCL node

---

GETTING_STARTED.md
README.md
beluga_benchmark/CMakeLists.txt
beluga_benchmark/package.xml
beluga_system_tests/CMakeLists.txt
beluga_system_tests/package.xml

Closes #95. Depends on #223. This patch completes ROS Noetic support work.

Wrap up ROS Noetic support

---

.github/workflows/ci_pipeline.yml
beluga/docs/CMakeLists.txt
beluga/package.xml
docker/images/humble/Dockerfile
docker/images/noetic/Dockerfile
docker/images/rolling/Dockerfile

Fixes #226.
We will print a warning if doxygen is not installed and documentation dependencies can now be installed via rosdep.

List documentation deps in package.xml

---

GETTING_STARTED.md
INSTALLING.md
README.md

Add installation guide

---

.flake8
.pre-commit-config.yaml
beluga_amcl/package.xml
docker/images/noetic/Dockerfile

Connected to #132 and builds on top of #236.

Remove ament_flake8 from pre-commit hooks

---

.github/workflows/ci_pipeline.yml
.pre-commit-config.yaml
GETTING_STARTED.md
README.md
beluga_amcl/package.xml
docker/images/noetic/Dockerfile
tools/check_copyright.py

Closes #132.
I couldn't find a pre-commit hook that I liked, so I wrote one... It isn't half bad IMO.
The options I considered were:
- https://github.com/leoll2/copyright_notice_precommit
- https://github.com/sbrunner/hooks

Replace ament_copyright with local script

---

beluga_example/models/turtlebot.model.yaml

#230 is fixed, but the simulated odometry noise is still too high for the simulation to be usable.

Reduce simulated odometry noise

---

README.md

Follow-up to https://github.com/Ekumen-OS/beluga/pull/213#issuecomment-1606269391.
The video encoding works on Firefox and Chrome.

Update video in README.md

---

.github/workflows/ci_pipeline.yml
.github/workflows/docker_ci_pipeline.yml
.github/workflows/weekly_pipeline.yml
GETTING_STARTED.md
docker/files/iron.repos
docker/images/iron/Dockerfile

Closes #219.
Adds a Dockerfile for Iron Irwini and updates the CI infrastructure. Moves the Rolling build to a weekly pipeline.

Add ROS 2 Iron CI infrastructure

---

beluga_amcl/src/amcl_node.cpp
beluga_amcl/src/amcl_nodelet.cpp
beluga_system_tests/test/test_system.cpp

Transform points in laser frame to robot frame

---

beluga/include/beluga/mixin/utility.hpp
beluga/include/beluga/primitives.hpp
beluga/include/beluga/type_traits/particle_traits.hpp
beluga/include/beluga/type_traits/tuple_traits.hpp
beluga/include/beluga/utility/forward_like.hpp
beluga/test/beluga/CMakeLists.txt
beluga/test/beluga/mixin/test_utility.cpp
beluga/test/beluga/test_primitives.cpp
beluga/test/beluga/type_traits/test_particle_traits.cpp
beluga/test/beluga/type_traits/test_tuple_traits.cpp
beluga/test/beluga/utility/test_forward_like.cpp

Meta-programming magic to better define the particle concept and constraints (with tests!).

What is a particle?

---

beluga/test/beluga/CMakeLists.txt
beluga/test/beluga/sensor/data/test_laser_scan.cpp
beluga/test/beluga/utility/test_forward_like.cpp

Add a missing test file to the gtest target.
Remove incorrect assert that prevented us from creating debug builds.

Minor fixes to forward_like test

---

beluga/include/beluga/definitions.hpp
beluga/include/beluga/detail/epilogue.hpp
beluga/include/beluga/detail/prologue.hpp
beluga/include/beluga/views/sample.hpp
beluga/test/beluga/CMakeLists.txt
beluga/test/beluga/views/test_sample.cpp

This adds a (with-replacement) sample view that generates an infinite range compatible with particle filter algorithms.

Add sample view

---

beluga/include/beluga/tuple_vector.hpp
beluga/include/beluga/type_traits/particle_traits.hpp
beluga/include/beluga/type_traits/tuple_traits.hpp
beluga/include/beluga/views/sample.hpp
beluga/test/beluga/test_tuple_vector.cpp
beluga/test/beluga/views/test_sample.cpp

Make sure to set weight equal to 1 after sampling from a particle set.

Fix sample view

---

beluga_system_tests/test/test_system_new.cpp

Run system tests with parallel execution enabled

---

beluga/include/beluga/actions.hpp
beluga/include/beluga/actions/normalize.hpp
beluga/test/beluga/CMakeLists.txt
beluga/test/beluga/actions/test_normalize.cpp
beluga_system_tests/test/test_system_new.cpp

Add normalize action

---

beluga_ros/cmake/ament.cmake
beluga_ros/setup.cfg
beluga_ros/src/beluga_ros/__init__.py
beluga_ros/src/beluga_ros/conversion_utils.py
beluga_ros/src/beluga_ros/occupancy_grid_to_ndt.py

Precisely what the title says. A small addition to #332.

Turn beluga_ros into a Python package

---

beluga/include/beluga/sensor/data/sparse_value_grid.hpp
beluga/test/beluga/CMakeLists.txt
beluga/test/beluga/sensor/data/test_sparse_value_grid.cpp

Adds a new data type to represent a 2D sparse value grid.

Add sparse value grid implementation

---

beluga/include/beluga/algorithm/amcl_core.hpp
beluga/test/beluga/CMakeLists.txt
beluga/test/beluga/algorithm/test_amcl_core.cpp

Adds a fully typed generic AMCL pipeline that can be used with any motion model, sensor model, random state generator, etc.

Add a core AMCL pipeline

---

beluga/test/beluga/sensor/data/test_occupancy_grid.cpp
beluga/test/beluga/views/test_random_intersperse.cpp
docker/images/rolling/Dockerfile

ROS 2 Rolling Ridley has moved on from Ubuntu Jammy. This patch updates Beluga packages to follow Rolling to Ubuntu Noble.
The build is not quite fixed yet because not all our dependencies are available yet (or even build) for Rolling on Noble.

Transition Beluga to Noble with Rolling

---

docs/conf.py

This patch fixes https://ekumen-os.github.io/beluga styling, which #346 broke.

Configure Sphinx for Github Pages publication

---

beluga_amcl/test/test_ndt_amcl_node.cpp

Follow-up to #345. This spurious include was left behind.

Remove ament_index_cpp dependency

---

beluga_example/launch/utils/flatland.launch
beluga_example/launch/utils/flatland_launch.py
beluga_example/params/default_ndt.ros2.yaml

Precisely what the title says. Not sure how this bug came this far along.

Remap `/turtlebot/scan` to `/scan` for Flatland

---

beluga_tutorial/package.xml
beluga_tutorial/src/main.cpp

Minor changes to the tutorial code to reduce duplication.

Reduce duplication when using `yaml-cpp`

---

.github/workflows/docker_ci_pipeline.yml
beluga_tutorial/package.xml

Prevent attempting to rosdep install a nonexistent package in ROS Noetic. Also update docker pipeline to trigger on changes to package.xml files across the repository.
Fixes https://build.ros.org/job/Ndev__beluga__ubuntu_focal_amd64/22/console

Add ROS 2 condition for `yaml_cpp_vendor` package

---

beluga/include/beluga/sensor/ndt_sensor_model.hpp

This change improves compatibility with 32-bit platforms (`armhf`).
Related to #389.

Add cast from `hsize_t` to `size_t`

---

beluga_tutorial/src/main.cpp

Adapt the main code to the names used by the key concepts.
This PR will wait for #390 to be merged into the main branch.

Adapt beluga_tutorial code to key concepts

---

beluga_amcl/src/ndt_amcl_node.cpp
beluga_example/params/default_ndt.ros2.yaml

Change default params to match the ones that were empirically tested and validated

Change NDT sensor model default params

---

beluga/include/beluga/sensor/data/ndt_cell.hpp
beluga/include/beluga/sensor/ndt_sensor_model.hpp
beluga/test/beluga/sensor/test_ndt_model.cpp

Small tweaks to enable NDT sensor model for SE3 states and 3D lidar returns.

Add 3D NDT sensor model and tests.

---

beluga/include/beluga/algorithm/estimation.hpp
beluga/test/beluga/algorithm/test_estimation.cpp

Exactly what the title states. 

Extend `beluga::estimate` for SE3

---

beluga/include/beluga/algorithm/spatial_hash.hpp
beluga/test/beluga/test_spatial_hash.cpp

Support for spatial hashing SE3d objects 

Spatial hash for SE3

---

beluga/include/beluga/sensor/data/landmark_map.hpp
beluga/test/beluga/sensor/data/test_landmark_map.cpp

This patch de-duplicates (and reuses) some of the code over at https://github.com/Ekumen-OS/beluga-demos.

Add implicit boundaries `LandmarkMap` constructor

---

beluga_amcl/cmake/ament.cmake
beluga_amcl/include/beluga_amcl/amcl_node.hpp
beluga_amcl/include/beluga_amcl/ndt_amcl_node.hpp
beluga_amcl/include/beluga_amcl/ros2_common.hpp
beluga_amcl/src/amcl_node.cpp
beluga_amcl/src/ndt_amcl_node.cpp
beluga_amcl/src/ros2_common.cpp
beluga_amcl/test/cmake/ament.cmake
beluga_amcl/test/test_ros2_common.cpp

Dedupe some of the shared code between nodes

---

beluga_amcl/include/beluga_amcl/amcl_node.hpp
beluga_amcl/include/beluga_amcl/ndt_amcl_node.hpp
beluga_amcl/include/beluga_amcl/ndt_amcl_node_3d.hpp
beluga_amcl/src/amcl_node.cpp
beluga_amcl/src/ndt_amcl_node.cpp
beluga_amcl/src/ndt_amcl_node_3d.cpp

Precisely what the title says. This patch:
- copes with `message_filters` header deprecations
- copes with `rclcpp::Node::create_service` API removals

Fix Rolling builds

---

docs/guides/using-beluga-amcl.md

This patch adds a Beluga AMCL usage guide, pending since #346.

Add Beluga AMCL usage guide

---

docs/guides/using-beluga-amcl.md

Polish Beluga AMCL user guide

---

beluga/include/beluga/actions/overlay.hpp

Rewrite overlay function following the guidelines in #441.

Rewrite overlay action

---

README.md
docs/index.md

Precisely what the title says. This patch updates both the repository README and the documentation index page to show a slightly more enticing video of Beluga in action.

Update front facing videos

---

.github/workflows/ci_pipeline.yml
.github/workflows/weekly_pipeline.yml

Precisely what the title says. We do not have strict control over dependencies. Weekly CI runs should also validate coverage, particularly during periods of low activity.

Complete weekly CI pipeline
